name: Deploy Drupal

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Image
        run: |
          docker build -t drupal-app -f docker/php/Dockerfile .

      - name: Tag Image
        run: |
          docker tag drupal-app:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/drupal-app:latest

      - name: Push Image1
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/drupal-app:latest

      - name: Trigger Auto Scaling refresh
        run: |
          STATUS=$(aws autoscaling describe-instance-refreshes \
            --auto-scaling-group-name himmat-autoscale \
            --query 'InstanceRefreshes[0].Status' \
            --output text)

          if [ "$STATUS" = "InProgress" ]; then
            echo "Instance refresh already running. Skipping."
          else
            aws autoscaling start-instance-refresh \
              --auto-scaling-group-name himmat-autoscale
          fi

